# Generated by Django 2.0.7 on 2018-07-06 01:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Guild',
            fields=[
                ('guild_id', models.IntegerField(primary_key=True, serialize=False)),
            ],
        ),
        migrations.CreateModel(
            name='GuildCustomCommands',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.IntegerField(choices=[(1, 'Text')], default=1)),
                ('value', models.CharField(max_length=2000)),
                ('guild', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='lbwebsite.Guild')),
            ],
        ),
        migrations.CreateModel(
            name='GuildPrefix',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('prefix', models.CharField(max_length=10)),
                ('guild', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='lbwebsite.Guild')),
            ],
        ),
        migrations.CreateModel(
            name='GuildServers',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('region', models.IntegerField(choices=[((1,), 'US'), ((2,), 'EU'), ((3,), 'TW'), (4, 'KR')], default=(1,))),
                ('server_slug', models.CharField(max_length=50)),
                ('guild_name', models.CharField(max_length=50, null=True)),
                ('default', models.BooleanField(default=False)),
                ('guild', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='lbwebsite.Guild')),
            ],
        ),
    ]
