# Generated by Django 2.0.7 on 2018-07-07 22:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lbwebsite', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='guild',
            name='name',
            field=models.CharField(default='', max_length=200),
            preserve_default=False,
        ),
    ]
