# Generated by Django 2.0.7 on 2018-08-11 16:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lbwebsite', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='RealmConnected',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('server_slug', models.CharField(max_length=50)),
                ('connected_realm', models.ManyToManyField(related_name='_realmconnected_connected_realm_+', to='lbwebsite.RealmConnected')),
            ],
        ),
    ]
