# Generated by Django 2.0.7 on 2018-07-08 05:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('lbwebsite', '0002_guildcustomcommand_name'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='guildcustomcommand',
            unique_together={('guild', 'name')},
        ),
    ]
