# Generated by Django 2.0.7 on 2018-07-08 00:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('lbwebsite', '0002_guild_name'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='character',
            unique_together={('region', 'server_slug', 'name')},
        ),
    ]
