# Generated by Django 2.0.7 on 2018-07-08 00:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lbwebsite', '0003_auto_20180707_2022'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='character',
            name='main_for_guild',
        ),
        migrations.AddField(
            model_name='character',
            name='main_for_guild',
            field=models.ManyToManyField(to='lbwebsite.Guild'),
        ),
    ]
