# Generated by Django 2.0.7 on 2018-07-08 05:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lbwebsite', '0003_auto_20180708_0117'),
    ]

    operations = [
        migrations.AlterField(
            model_name='discordguild',
            name='guild_id',
            field=models.BigIntegerField(primary_key=True, serialize=False),
        ),
    ]
