# Generated by Django 2.0.7 on 2018-09-22 03:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('lbwebsite', '0003_realmconnected_region'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='guildprefix',
            unique_together={('guild', 'prefix')},
        ),
        migrations.AlterUniqueTogether(
            name='guildserver',
            unique_together={('guild', 'region', 'server_slug', 'guild_name')},
        ),
    ]
