# Generated by Django 2.0.7 on 2018-10-08 14:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('lbwebsite', '0005_auto_20181008_1034'),
    ]

    operations = [
        migrations.AddField(
            model_name='guildrank',
            name='wow_guild',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='lbwebsite.GuildServer'),
            preserve_default=False,
        ),
    ]
