# Generated by Django 2.0.7 on 2018-10-08 14:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('lbwebsite', '0006_guildrank_wow_guild'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='guildrank',
            unique_together={('guild', 'wow_guild', 'rank_id')},
        ),
    ]
