# Generated by Django 2.0.7 on 2018-10-08 20:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('lbwebsite', '0007_auto_20181008_1049'),
    ]

    operations = [
        migrations.CreateModel(
            name='GuildSetting',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('setting_name', models.CharField(max_length=100)),
                ('setting_value', models.CharField(max_length=1000)),
                ('guild', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='lbwebsite.DiscordGuild')),
            ],
        ),
        migrations.AlterUniqueTogether(
            name='guildsetting',
            unique_together={('guild', 'setting_name')},
        ),
    ]
